Problem 1: Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 2 arrays, each with 6 elements:

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#code here
newArr = arr.reshape(2, 6)
print(newArr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Problem 2: Convert the following 1-D array into a 3d Array with 1 X 3 elements

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#code here
newArr = arr.reshape(1, 3, -1)
print(newArr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


Problem 3: Iterate on the elements of the following 3-D array and add 12 if the number is odd and substract -12 if the number is even and print it.


In [18]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#code here
for x in np.nditer(arr):
    if x % 2 != 0:    #if the number is odd
        print(x + 12)
    else:             #if the number is even
        print(x - (-12))

13
14
15
16
17
18
19
20
21
22
23
24


Problem 4 : Join two 2-D arrays along rows (axis=1):

In [25]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

arr2 = np.array([[5, 6], [7, 8],[70,80],[90,100],[110,120]])

#code here
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[  1   2   5   6]
 [  3   4   7   8]
 [  5   6  70  80]
 [  7   8  90 100]
 [  9  10 110 120]]


Problem 5 : Stack two 2-D Array along columns

In [27]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

arr2 = np.array([[5, 6], [7, 8],[70,80],[90,100],[110,120]])
#code here
arr = np.vstack((arr1, arr2))
print(arr)

[[  1   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [  5   6]
 [  7   8]
 [ 70  80]
 [ 90 100]
 [110 120]]


Problem 5 : Stack two 2-D Array along depth

In [52]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

arr2 = np.array([[5, 6], [7, 8],[70,80],[90,100],[110,120]])
#code here
arr = np.dstack((arr1, arr2))
print(arr)

[[[  1   5]
  [  2   6]]

 [[  3   7]
  [  4   8]]

 [[  5  70]
  [  6  80]]

 [[  7  90]
  [  8 100]]

 [[  9 110]
  [ 10 120]]]


Problem 6 : Create a filter array for the 1d array. If the number is even then store True in then filter array else False
And then filter the initial array using the filter array.

In [31]:

import numpy as np

arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#code here

#this is our filter array
filterArr = arr % 2 == 0 #if number is even then store True
print("Filter Array:", filterArr)

print()

newArr = arr[filterArr]
print("New Array:", newArr)

Filter Array: [False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]

New Array: [42 44 46 48 50  2  4  6  8 10]


Problem 7 : Generate 50 random numbers and store it in numpy array and then apply the same operations in problem 6

In [46]:
from numpy import random

#code here

#generate 50 random numbers and store them
arr = random.randint(1000, size=(50))    #random numbers into an array

filterArr = arr % 2 == 0                 #generate our filter array
print("Filter Arr:", filterArr)

print()

newArr = arr[filterArr]
print("New Array:", newArr)              #generate our new array based on the filter array

Filter Arr: [ True False  True False  True False  True  True False False False False
  True False False  True  True  True  True  True  True  True  True False
 False False False  True  True False False  True False False False  True
  True  True  True False False False False  True False  True False False
 False False]

New Array: [496 844 518  12 928 678 936 808 102 358 446 776 264 286 362 132 414 566
 490 456 642 848 520]


Problem 8 :  Slice from the index 3 from the end to index 1 from the end


In [53]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

#code here
print(arr1[-4:-1])

[[3 4]
 [5 6]
 [7 8]]


Problem 9 : Return every two other element from index 1 to index 5:

In [48]:
import numpy as np
arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[1:5:2])

[42 44]


Problem 10 : Generate a random permutation of elements of following array

In [51]:
import numpy as np
from numpy import random
arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#code here
newArr = random.permutation(arr)
print(newArr)

[47 43  3  7  6  5 42  9 49  8 44 41  2  1 45 10 48 46 50  4]
